version: '3.8'

services:

  zookeeper:
    container_name: andersen_zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    container_name: andersen_kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mongo:
    container_name: andersen_mongo
    image: mongo
    ports:
      - '27017:27017'
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=andersen
      - MONGO_INITDB_ROOT_PASSWORD=andersen

  game-server-na:
    container_name: game_server_na
    build: game-server
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - mongo
    environment:
      - SERVER_NAME=NA
      - SERVER_PORT=8081
      - KAFKA_HOST=kafka:9092

  game-server-weu:
    container_name: game_server_weu
    build: game-server
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - mongo
    environment:
      - SERVER_NAME=WEU
      - SERVER_PORT=8082
      - KAFKA_HOST=kafka:9092

  game-server-eeu:
    container_name: game_server_eeu
    build: game-server
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - mongo
    environment:
      - SERVER_NAME=EEU
      - SERVER_PORT=8083
      - KAFKA_HOST=kafka:9092

  game-stat:
    container_name: game_stat
    build: game-stat
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - mongo
    environment:
      - KAFKA_HOST=kafka:9092
      - MONGO_HOST=mongo